import { useState } from 'react'
import { Link } from 'react-router-dom'
import { PageContainer } from '../components/layout/PageContainer'
import { ComparisonTable, ExampleBlock, LessonHeader, LessonNavigation, LessonSection, LearningObjectives } from '../components/ui/LessonSystem'

const budgetRows = [['Income', 'Part-time work and allowance', '$1,200'], ['Fixed expense', 'Shared accommodation', '$420'], ['Variable expense', 'Food and transport', '$260'], ['Flexible spending', 'Entertainment and social plans', '$120'], ['Savings', 'Goal contribution', '$150']]

export function BudgetingBasics() {
  const [answer, setAnswer] = useState('')
  const correct = answer === 'b'
  return <PageContainer className="lesson-page">
    <LessonHeader eyebrow="Lesson 01 · Foundations" title="What is a budget?" intro="A budget is a simple plan for the money you expect to receive and the way you expect to use it. This lesson builds the foundation for every other topic in BudgetBasics." asset="budgeting-basics.png" alt="Illustration representing a student organising income and expenses." breadcrumbs={[{ label: 'Home', to: '/' }, { label: 'Learn', to: '/budgeting-basics' }, { label: 'Budgeting Basics' }]} />
    <LearningObjectives items={['Explain what a budget helps you understand.', 'Separate income, fixed expenses, variable expenses, wants and savings.', 'Build and review a simple monthly plan.']} />
    <div className="lesson-reading">
      <LessonSection number={1} eyebrow="Start with the purpose" title="What is a budget?"><p>A budget puts expected income and planned spending in one place. It helps you see whether your money is likely to cover essentials, flexible choices and future goals before the month is over.</p><p>For a student, a budget can make school supplies, transport, food, entertainment and saving visible together. It is a planning tool, not a judgement about how someone should live.</p></LessonSection>
      <LessonSection number={2} eyebrow="Student life" title="Why students need a budget"><p>Student money can arrive at different times and be used for many competing priorities. Listing those priorities makes trade-offs easier to discuss and adjust.</p><ExampleBlock title="A realistic situation"><p>Amara receives an allowance at the start of the month and earns occasional money from tutoring. She first plans for transport, meals and course materials, then decides how much can go toward a concert and a savings goal.</p></ExampleBlock></LessonSection>
      <LessonSection number={3} eyebrow="Money coming in" title="Understanding income"><p>Income is money available to use. It may be regular, such as a scheduled allowance, or irregular, such as occasional part-time work. Record irregular income carefully: only count money you reasonably expect to receive.</p><ul className="lesson-list"><li>Allowance or family support</li><li>Part-time work, tutoring or freelance work</li><li>Scholarships, grants or other legitimate support</li></ul></LessonSection>
      <LessonSection number={4} eyebrow="Money going out" title="Understanding expenses"><p>Expenses are payments or purchases. Fixed expenses tend to stay similar, while variable expenses can change with use, prices or choices.</p><ComparisonTable columns={['Type', 'Meaning', 'Student example']} rows={[[ 'Fixed', 'Usually the same or predictable each period.', 'Room rent or a phone plan' ], [ 'Variable', 'Changes from period to period.', 'Food, transport or electricity' ]]} /></LessonSection>
      <LessonSection number={5} eyebrow="Make choices visible" title="Needs, wants and savings"><p>Needs support health, safety, education or basic responsibilities. Wants are optional choices that can often be delayed or changed. Savings is money set aside for a future goal or unexpected cost.</p><p>The same item can depend on context. A phone may be important for school, while a new phone model may be a want. Continue with the <Link className="lesson-inline-link" to="/needs-vs-wants">Needs vs Wants lesson</Link> to practise the decision.</p></LessonSection>
      <LessonSection number={6} eyebrow="Build the plan" title="How to build a monthly budget"><ol className="lesson-steps"><li><strong>Identify income.</strong> List money you expect to have available.</li><li><strong>List essential expenses.</strong> Start with obligations and basic needs.</li><li><strong>Identify flexible spending.</strong> Add choices that can be adjusted.</li><li><strong>Set aside savings.</strong> Choose a realistic amount for a future goal.</li><li><strong>Review the result.</strong> If planned spending is greater than income, change the flexible categories first.</li></ol></LessonSection>
      <LessonSection number={7} eyebrow="Educational example" title="Sample student monthly budget"><p>These figures are an illustrative example only. They do not describe typical student spending.</p><ComparisonTable columns={['Category', 'Example item', 'Amount']} rows={budgetRows} /></LessonSection>
      <LessonSection number={8} eyebrow="Learn from the month" title="Review the budget"><p>At the end of the period, compare the plan with what happened. Ask: Did I spend more than planned? Which categories were highest? Did I save what I intended? Which expenses could be reduced? What should change next month?</p></LessonSection>
      <div className="lesson-takeaways"><span className="lesson-eyebrow">Key takeaways</span><ul><li>A budget connects expected income with planned choices.</li><li>Fixed and variable expenses need different kinds of planning.</li><li>A budget is useful when it is reviewed and adjusted.</li></ul></div>
      <section className="lesson-check-section"><h2>Knowledge check</h2><p>Which item is most likely to be a variable expense?</p><div className="check-options">{[['a', 'A monthly rent payment'], ['b', 'Transport used during the month'], ['c', 'A fixed school fee']].map(([value, label]) => <button key={value} className={answer === value ? 'is-selected' : ''} type="button" onClick={() => setAnswer(value)}>{value.toUpperCase()}. {label}</button>)}</div>{answer && <p className={correct ? 'check-feedback correct' : 'check-feedback'}>{correct ? 'Correct. Transport can change based on use.' : 'Not quite. Think about which cost can change from month to month.'}</p>}</section>
      <LessonNavigation next={{ label: 'Needs vs Wants', to: '/needs-vs-wants' }} />
    </div>
  </PageContainer>
}
