import { Link } from 'react-router-dom'
import { EducationalImage } from '../components/ui/EducationalImage'

const lessons = [
  ['01', 'Budgeting Basics', 'Understand income, expenses and the shape of a monthly plan.', '/budgeting-basics'],
  ['02', 'Needs vs Wants', 'Practise making thoughtful choices when money is limited.', '/needs-vs-wants'],
  ['03', 'The 50/30/20 Rule', 'Explore an educational guideline for organising priorities.', '/50-30-20'],
  ['04', 'Savings Goals', 'Turn a goal into a target, timeline and regular contribution.', '/savings-goals'],
  ['05', 'Expense Planning', 'Learn what tracking reveals, then try the session-only planner.', '/expense-planner'],
  ['06', 'Common Money Mistakes', 'Recognise common patterns and choose a better next step.', '/money-mistakes'],
]

export function Home() {
  return <main className="home-reconstruction">
    <section className="home-hero-reconstruction"><div className="page-container home-hero-grid"><div className="home-hero-copy"><span className="lesson-eyebrow">BudgetBasics · Student financial literacy</span><h1>Learn to make a plan for your money.</h1><p>Build practical money skills through short lessons, realistic examples and tools that help you practise what you have learned.</p><div className="home-hero-actions"><Link className="home-primary-link" to="/budgeting-basics">Start learning</Link><Link className="home-secondary-link" to="/needs-vs-wants">Explore the lessons</Link></div></div><EducationalImage asset="student-budget-planning.jpg" alt="Student planning a budget at a desk with a laptop and notebook." className="home-hero-image-reconstruction" loading="eager" /></div></section>

    <section className="home-introduction page-container"><div className="home-section-label"><span className="lesson-eyebrow">What is BudgetBasics?</span><h2>A calm place to learn the decisions behind a budget.</h2></div><div className="home-introduction-copy"><p>BudgetBasics is an educational website for students who want a clearer way to think about income, spending, saving and everyday financial habits.</p><p>Each topic follows a simple rhythm: understand the idea, see an example, try an activity and reflect on what comes next.</p><Link className="lesson-inline-link" to="/about">Learn about the project →</Link></div></section>

    <section className="home-learning-reconstruction page-container" aria-labelledby="home-learning-title"><div className="home-section-heading-reconstruction"><div><span className="lesson-eyebrow">The curriculum</span><h2 id="home-learning-title">What you will learn</h2></div><p>Start with the foundation and move through the topics in order, or choose the lesson that answers your question today.</p></div><div className="home-learning-list">{lessons.map(([number, title, description, to]) => <Link className="home-learning-row" to={to} key={title}><span className="home-path-number">{number}</span><span><strong>{title}</strong><small>{description}</small></span><span aria-hidden="true">→</span></Link>)}</div></section>

    <section className="home-featured-lesson"><div className="page-container home-featured-grid"><EducationalImage asset="budgeting-basics.png" alt="Illustration representing a student organising a budget." className="home-featured-image" /><div><span className="lesson-eyebrow">Featured lesson · 8 minutes</span><h2>Begin with Budgeting Basics</h2><p>Understand what a budget does, how income and expenses fit together, and why reviewing a plan matters.</p><ul><li>Identify regular and irregular income.</li><li>Compare fixed and variable expenses.</li><li>Build a simple monthly plan.</li></ul><Link className="home-primary-link" to="/budgeting-basics">Read the lesson →</Link></div></div></section>

    <section className="home-tools-reconstruction page-container" aria-labelledby="home-tools-title"><div className="home-section-heading-reconstruction"><div><span className="lesson-eyebrow">Learn by doing</span><h2 id="home-tools-title">Practical tools</h2></div><p>Use each tool after the explanation to test an idea with an illustrative scenario. Nothing is saved as a financial record.</p></div><div className="home-tools-editorial"><Link to="/50-30-20"><span className="home-tool-index">01</span><strong>50/30/20 Calculator</strong><p>See how a guideline changes when income or percentages change.</p><span className="lesson-inline-link">Try the calculator →</span></Link><Link to="/savings-goals"><span className="home-tool-index">02</span><strong>Savings Goal Planner</strong><p>Turn a target amount into a contribution and estimated timeline.</p><span className="lesson-inline-link">Plan a goal →</span></Link><Link to="/expense-planner"><span className="home-tool-index">03</span><strong>Expense Planner</strong><p>Record sample expenses and review the balance during this session.</p><span className="lesson-inline-link">Plan expenses →</span></Link><Link to="/needs-vs-wants"><span className="home-tool-index">04</span><strong>Needs vs Wants Activity</strong><p>Classify everyday student expenses and compare your reasoning.</p><span className="lesson-inline-link">Practise decisions →</span></Link></div></section>

    <section className="home-knowledge-band"><div className="page-container home-knowledge-grid"><div><span className="lesson-eyebrow">Financial knowledge</span><h2>Good planning starts with useful questions.</h2><p>Before you buy, ask what the expense is for, whether it fits the plan, and what other priority it might affect.</p></div><div className="home-question-list"><p><strong>Budgeting</strong><span>What money is coming in, and what must it cover?</span></p><p><strong>Spending</strong><span>Is this a need, a want, or a choice that needs more thought?</span></p><p><strong>Saving</strong><span>What specific goal would make setting money aside meaningful?</span></p></div></div></section>

    <section className="home-infographic page-container"><div><span className="lesson-eyebrow">Featured visual guide</span><h2>Understanding the 50/30/20 rule</h2><p>The 50/30/20 framework is an educational guideline: a way to begin thinking about needs, wants and savings. It is not a universal requirement.</p><Link className="lesson-inline-link" to="/50-30-20">Read the guide and try the calculator →</Link></div><EducationalImage asset="50-30-20-rule.png" alt="Infographic explaining the educational 50/30/20 budgeting guideline." className="home-infographic-image" /></section>

    <section className="home-scenario page-container"><div><span className="lesson-eyebrow">Illustrative scenario</span><h2>You receive money for the month. What should happen first?</h2><p>Start by identifying essential expenses, then consider flexible spending and a realistic savings contribution. The right amounts depend on the situation; this is a way to practise the order of thinking.</p></div><div className="home-scenario-table"><div><span>Income</span><strong>$1,200</strong></div><div><span>Essentials</span><strong>$680</strong></div><div><span>Flexible spending</span><strong>$220</strong></div><div><span>Savings goal</span><strong>$150</strong></div><small>Sample figures for learning only.</small></div></section>

    <section className="home-tip-reconstruction"><div className="page-container"><span className="lesson-eyebrow">Money tip</span><h2>A plan is useful because it can be reviewed.</h2><p>If a month does not go as expected, compare the plan with what happened and adjust the next plan. A change is information, not a failure.</p></div></section>
    <section className="home-start-learning page-container"><div><span className="lesson-eyebrow">Next step</span><h2>Start with a clear definition of a budget.</h2></div><Link className="home-primary-link" to="/budgeting-basics">Start Budgeting Basics →</Link></section>
  </main>
}
